metal:
  children:
    masters:
      hosts:
        metal0: {ansible_host: 192.168.3.110, mac: '26:00:5f:0e:a6:c5', disk: sda, network_interface: eno1}
        metal1: {ansible_host: 192.168.3.111, mac: '66:30:1c:84:1e:d2', disk: sda, network_interface: eno1}
        metal2: {ansible_host: 192.168.3.112, mac: '1e:18:0c:4b:2f:c7', disk: sda, network_interface: eno1}
          #    workers:
          #hosts:
          # metal3: {ansible_host: 192.168.1.113, mac: '00:23:24:d1:f4:d6', disk: sda, network_interface: eno1}
